version : "3"

services:
  web:
    build: ./web
    command: gunicorn -w 3 -b 0.0.0.0:8000 application:application
    ports:
      - 8000

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /root/docker-nginx-scale/nginx/ssl:/ssl
      - /root/docker-nginx-scale/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
