FROM nginx

# Remove the default nginx.conf
# RUN rm /etc/nginx/conf.d/default.conf
# RUN rm /etc/nginx/conf.d/nginx.conf
# RUN rm /etc/nginx/sites-enabled/default
# Replace with our own nginx.conf
COPY nginx.conf /etc/nginx